Works perfectly on OSX with -fno-pie :) Thanks, @jensnockert!

diff --git a/Makefile.osx b/Makefile.osx
--- a/Makefile.osx
+++ b/Makefile.osx
@@ -1,21 +1,30 @@
 .PHONY: all clean
 
-CELLAR:=/usr/local/Cellar
-GETTEXT:=$(CELLAR)/gettext/0.18.3
-BINUTILS:=$(CELLAR)/binutils/2.23.2
+GETTEXT:=$(shell brew info gettext | grep 'Cellar' | head -1 | cut -d ' ' -f 1)
+ifeq ($(GETTEXT),)
+  echo "gettext not found! install it via 'brew install gettext'"
+  exit 1
+endif
 
+BINUTILS:=$(shell brew info binutils | grep 'Cellar' | head -1 | cut -d ' ' -f 1)
+ifeq ($(BINUTILS),)
+  echo "binutils not found! install it via 'brew install binutils'"
+  exit 1
+endif
+
+DEBUG_FLAGS:=-fno-pie -g
 OSX_FLAGS:=-I$(GETTEXT)/include -I$(BINUTILS)/include -L$(GETTEXT)/lib -L$(BINUTILS)/lib/ -L$(BINUTILS)/lib/x86_64/
 
 all: backtrace.dylib test
 
 backtrace.dylib : backtrace.c
-	gcc ${OSX_FLAGS} -DBUILDING_BACKTRACE_LIB -fPIC -O2 -shared -Wall -o $@ $^ -lbfd -lintl -liberty -lz
+	gcc ${DEBUG_FLAGS} ${OSX_FLAGS} -DBUILDING_BACKTRACE_LIB -fPIC -O2 -shared -Wall -o $@ $^ -lbfd -lintl -liberty -lz
 
 test : test.c
-	gcc -gdwarf-2 -Wall -o $@ $^
+	gcc ${DEBUG_FLAGS} -Wall -o $@ $^
 
 otest : otest.ooc
-	rock -v -g -o=$@ $^
+	rock -v -g +-fno-pie -o=$@ $^
 
 clean :
 	@rm -f backtrace.dylib test otest
